USE SharkTankDWH;
GO

IF NOT EXISTS ( SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'stage' AND t.name = 'pitch_raw_data' )
BEGIN
    CREATE TABLE stage.pitch_raw_data ( season_number	                    INT,
                                        startup_name	                    NVARCHAR(250),
                                        episode_number	                    INT,
                                        pitch_number	                    INT,
                                        season_start	                    DATE,
                                        season_end	                        DATE,
                                        original_air_date	                DATE,
                                        industry	                        NVARCHAR(100),
                                        business_description	            NVARCHAR(MAX),
                                        company_website	                    NVARCHAR(MAX),
                                        pitchers_gender	                    NVARCHAR(10),
                                        pitchers_average_age	            NVARCHAR(10),
                                        pitchers_city	                    NVARCHAR(100),
                                        pitchers_state	                    NVARCHAR(20),
                                        entrepreneur_names	                NVARCHAR(250),
                                        multiple_entrepreneurs	            BIT,
                                        us_viewership	                    FLOAT,
                                        original_ask_amount	                FLOAT,
                                        original_offered_equity	            FLOAT,
                                        valuation_requested	                FLOAT,
                                        got_deal	                        BIT,
                                        total_deal_amount	                FLOAT,
                                        total_deal_equity	                FLOAT,
                                        deal_valuation	                    FLOAT,
                                        number_of_sharks_in_deal	        INT,
                                        investment_amount_per_shark	        FLOAT,
                                        equity_per_shark	                FLOAT,
                                        royalty_deal	                    BIT,
                                        advisory_shares_equity	            FLOAT,
                                        loan	                            FLOAT,
                                        deal_has_conditions	                BIT,
                                        barbara_corcoran_investment_amount  FLOAT,
                                        barbara_corcoran_investment_equity	FLOAT,
                                        mark_cuban_investment_amount	    FLOAT,
                                        mark_cuban_investment_equity	    FLOAT,
                                        lori_greiner_investment_amount	    FLOAT,
                                        lori_greiner_investment_equity	    FLOAT,
                                        robert_herjavec_investment_amount	FLOAT,
                                        robert_herjavec_investment_equity	FLOAT,
                                        daymond_john_investment_amount	    FLOAT,
                                        daymond_john_investment_equity	    FLOAT,
                                        kevin_o_leary_investment_amount	    FLOAT,
                                        kevin_o_leary_investment_equity	    FLOAT,
                                        guest_investment_amount	            FLOAT,
                                        guest_investment_equity	            FLOAT,
                                        guest_name	                        NVARCHAR(100),
                                        barbara_corcoran_present	        BIT,
                                        mark_cuban_present	                BIT,
                                        lori_greiner_present	            BIT,
                                        robert_herjavec_present	            BIT,
                                        daymond_john_present	            BIT,
                                        kevin_o_leary_present	            BIT,
                                        guest_present                       BIT,
                                        import_date                         DATETIME DEFAULT GETDATE() );
END